---
# based on: https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139

# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: required

matrix:
  include:
    - os: linux
      dist: fedora
      sudo: required

language: go
go:
- "1.10"

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

# test and build
script: 
- go test -v -race ./...
