language: go

go:
- '1.10'

env:
  global:
  - secure: EKZGdOjYMHer7aPh52yliVFGW7rfgLjkeScdemE02LdTBTTvr5NKz4XFs6/GVm8hRMOlU3dhQqSnMPcx3wsHMKEX/CuUxBNSs450JErFO413nDU21WKX/4RSiewUfJ2dhUd0Rit4mVqe7urXSOV0C4jA5iRaSLJdERz0NqsT3VgXs0/KZTKqdRuYar8yY2AaQ2Yqa3UQPIcNhU3yO69U2Z+sJ9heZa+p/DZ0f7DktJ51RmMYmZUeDQx+sIrTKhHEk2THODTAey3rmd74vAvAaASnHtGCf5sacBGy6gdcboUXO91OMlmSiKOmMCFcq3SgXLOpRp41dx9iQV7EBT+9m5UvCfL8N/TtAM/q8FFNqPMsLSpiv2NgMX++rcOQwaY5QK7snuqOMwYaa1h8thecTUXp9ZwhpbaDRvrc5cS9+wN7GxYZblULI7E1eD++gsm2VGfJ05xRhE0Yw+lLQaAbZZB6mrIDthPFEQx87mwVISlFC16lfkmAGm9SyykGH2KzyORyvlNQwIQ4cuPYDErgUNoRSI4MX8dqjQPoHJkSx0euMMILpyamjmpr1OjogDndeF9oKSkezgx6ifYm+sLTA8n2i8TIK8RdvLdDqTnunwvsNihVoyujEhKE1kJgPWCQw5NKibnD8rIEtBQAN6/l5/EzUGlA/XiSSFtlRLv1LJE=
  - secure: teJQNCpJTPyowAI+zwkOW0ioE4/E9F9FSM1J/otF3JAYX30sctmW912zOA2UEkHQeMqf/1yU94va4WkI+YgTzeykwXaWTsGYhCW81fo9dKzCSpOwt8LMaZpDPzyBFiWg5G+qCj7qWGRUi7oSOMpT5ThUpnvCa8Ws8xUETtaEu6CpI4kKmVvNiv09tdxj69hVt9jmGqy6tdxTsUBzpttnlIfKAVnW7rOpqB9MN0v6XVE6aBhJFZVzu38YKd/V9XYO+EcGyuwpe70BX3PHKfTCyUIcZcKfxi1RHPYp0wDeSNn5BR8Pq/HxGKiAzkIKqDW21mLWBC1nohP3ZngFRXIWiE77fnySpkvBHyrB7Lc4HvY/EGXl4xARus+QeUcY35ayKW6U/UU0BZsN+lnzRuqkf4NBc2upuBqvFCcvcb1lECrWiEiii9hq3++ZndBi6WATjVoMDWaDYjb+t7+HrTCF7D5U0+wIfgChRn0zyQNLYPsiZl6uI30AGtJbJk2GC4oFP3dqpP07mxvAglltL4+9LvbKp8T4RBQqWc22mDzaa98WWTnLFL2Kfp8zENxLmfjdAU4UYjZOQtKitT0vnBMUj2WMS8EX4iMlpfHodlGQw0VAXjG4mZ8U1qtqhlpcD8BU+URXjWnWWPfq4YEGPsXq0v737g6vK0QjUHc5u1H8jh4=

matrix:
  include:
  - os: fedora
    dist: 28
    sudo: required

git:
  depth: 1

notifications:
  email: false

script:
- go test -v -race ./...

before_deploy:
 - dnf install -y git buildah runc podman

deploy:
  on:
    branch: release
  provider: script
  script: bash deploy.sh
