language: go

go:
- '1.10'

services:
  - docker

git:
  depth: 1

notifications:
  email: false

script:
- go test -v -race ./...

deploy:
  on:
    branch: release
  provider: script
  script: bash docker.sh
