language: go

go:
- '1.10'

env:
  global:
    secure: I7FS6VXZ+Z0UK1/YEaM5C9q554tyxqyIw4hVPHLJfNWHKVqddPgx0moMu5UTJFMe4AO9RbRDkSnOCr6bafrjg42FE/9m9fNlR9MQz350kCzj1O9DGe3+xqOTDJP9L0Ny0wwxX63823s+DPbX57SABnzD0528hljWu+dJo2OSbTFS9stNkcn0bfBXEpIPmuDAvf3CoY/XOMAYk8pAieFsrZB73qCS2d9du3zdyZlhNNmmpLyerIWajZzk5mJ7Cid9cuZ7YdxNgOhFLoPrjOJGsFOEo5lDEFo/QPHhE9F6pYE6xsoEmlTJnecqhCZcUoVrAFoIQQyYW+iWa437HLlM3cWNULs2RXfkGWy6rigWZ6Idun5IFbDAflIhhxlvjIw3UfFoHTqj+2HGmN/9HSp+ly6mIrD4lkJsf5hObGj2nl5Zgz60/7eQMyOYj82nNS/MCHayYYk11sFTAxQQxwF2ICMiW1wnNpl6hVWQJI9ZW72CBMqpRWW3HifpAF1UIlhZPSbYMJc+Df1LHtznnj1eQTeAc1pIGkA0I+DrurclO+2kaOmxwTw8+qVURaBAudYGTSgsdD1uMWb4mG+Peid7vFa529xhxnzX+ZoqGswcu64u3utEkmcw/elWwTA+JgO4gXTIfqVJftU4ZMqhfX+cYi3i00qR5Xi9LlQ8cGJFBdU=

matrix:
  include:
  - os: linux
    dist: fedora
    sudo: required

git:
  depth: 1

notifications:
  email: false

script:
- go test -v -race ./...

deploy:
  on:
    branch: release
  before_deployment:
  - dnf install -y git buildah runc podman
  provider: script
  script: bash deploy.sh
